-- MySQL Script generated by MySQL Workbench
-- 12/01/15 00:40:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema energoremotedb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `energoremotedb` ;

-- -----------------------------------------------------
-- Schema energoremotedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `energoremotedb` DEFAULT CHARACTER SET utf8 ;
USE `energoremotedb` ;

-- -----------------------------------------------------
-- Table `energoremotedb`.`Behaviors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `energoremotedb`.`Behaviors` ;

CREATE TABLE IF NOT EXISTS `energoremotedb`.`Behaviors` (
  `behaviorID` INT(11) NOT NULL AUTO_INCREMENT ,
  PRIMARY KEY (`behaviorID`)  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `energoremotedb`.`Positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `energoremotedb`.`Positions` ;

CREATE TABLE IF NOT EXISTS `energoremotedb`.`Positions` (
  `positionID` INT(11) NOT NULL AUTO_INCREMENT ,
  `positionX` INT(11) NOT NULL ,
  `positionY` INT(11) NOT NULL ,
  PRIMARY KEY (`positionID`)  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `energoremotedb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `energoremotedb`.`Users` ;

CREATE TABLE IF NOT EXISTS `energoremotedb`.`Users` (
  `userID` INT(11) NOT NULL AUTO_INCREMENT ,
  `name` NVARCHAR(140) NOT NULL ,
  `login` VARCHAR(100) NOT NULL ,
  `password` VARCHAR(32) NOT NULL ,
  `regDate` DATE NULL DEFAULT NULL ,
  PRIMARY KEY (`userID`)  ,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC)  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `energoremotedb`.`Settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `energoremotedb`.`Settings` ;

CREATE TABLE IF NOT EXISTS `energoremotedb`.`Settings` (
  `settingID` INT(11) NOT NULL AUTO_INCREMENT ,
  `azimuth` VARCHAR(45) NULL DEFAULT NULL ,
  `isColor` VARCHAR(45) NULL DEFAULT NULL ,
  `photosensor` VARCHAR(45) NULL DEFAULT NULL ,
  `brightWhite` VARCHAR(45) NULL DEFAULT NULL ,
  `brightRed` VARCHAR(45) NULL DEFAULT NULL ,
  `brightGreen` VARCHAR(45) NULL DEFAULT NULL ,
  `brightBlue` VARCHAR(45) NULL DEFAULT NULL ,
  `coefWhite` VARCHAR(45) NULL DEFAULT NULL ,
  `coefRGB` VARCHAR(45) NULL DEFAULT NULL ,
  `humanTimer` VARCHAR(45) NULL DEFAULT NULL ,
  `usePhotosensor` VARCHAR(45) NULL DEFAULT NULL ,
  `isWhite` VARCHAR(45) NULL DEFAULT NULL ,
  `OnOff` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`settingID`)  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `energoremotedb`.`Rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `energoremotedb`.`Rooms` ;

CREATE TABLE IF NOT EXISTS `energoremotedb`.`Rooms` (
  `roomID` INT(11) NOT NULL AUTO_INCREMENT ,
  `name` NVARCHAR(80) NOT NULL ,
  `backgroundURL` VARCHAR(200) NULL ,
  PRIMARY KEY (`roomID`)  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `energoremotedb`.`Groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `energoremotedb`.`Groups` ;

CREATE TABLE IF NOT EXISTS `energoremotedb`.`Groups` (
  `groupID` INT(11) NOT NULL AUTO_INCREMENT ,
  `userID` INT(11) NOT NULL ,
  `settingID` INT(11) NULL DEFAULT NULL ,
  `roomID` INT(11) NOT NULL ,
  `behaviorID` INT(11) NOT NULL ,
  `name` NVARCHAR(80) NOT NULL ,
  `positionID` INT NULL ,
  PRIMARY KEY (`groupID`)  ,
  INDEX `FkGroupsToUsers_idx` (`userID` ASC)  ,
  INDEX `FkGroupsToSettings_idx` (`settingID` ASC)  ,
  INDEX `FkGroupsToRoomID_idx` (`roomID` ASC)  ,
  INDEX `FkGroupsToBehaviors_idx` (`behaviorID` ASC)  ,
  INDEX `FkGroupsToPositions_idx` (`positionID` ASC)  ,
  CONSTRAINT `FkGroupsToUsers`
    FOREIGN KEY (`userID`)
    REFERENCES `energoremotedb`.`Users` (`userID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FkGroupsToSettings`
    FOREIGN KEY (`settingID`)
    REFERENCES `energoremotedb`.`Settings` (`settingID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FkGroupsToRoom`
    FOREIGN KEY (`roomID`)
    REFERENCES `energoremotedb`.`Rooms` (`roomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FkGroupsToBehaviors`
    FOREIGN KEY (`behaviorID`)
    REFERENCES `energoremotedb`.`Behaviors` (`behaviorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FkGroupsToPositions`
    FOREIGN KEY (`positionID`)
    REFERENCES `energoremotedb`.`Positions` (`positionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `energoremotedb`.`Devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `energoremotedb`.`Devices` ;

CREATE TABLE IF NOT EXISTS `energoremotedb`.`Devices` (
  `deviceID` INT(11) NOT NULL AUTO_INCREMENT ,
  `groupID` INT(11) NOT NULL ,
  `key` VARCHAR(20) NOT NULL ,
  `serial` INT(11) NOT NULL ,
  `positionID` INT(11) NULL DEFAULT NULL ,
  `settingID` INT(11) NOT NULL ,
  `version` VARCHAR(45) NULL DEFAULT NULL ,
  `name` NVARCHAR(80) NULL ,
  PRIMARY KEY (`deviceID`)  ,
  INDEX `FkDevicesToPositions_idx` (`positionID` ASC)  ,
  INDEX `FkDevicesToGroups_idx` (`groupID` ASC)  ,
  INDEX `FkDevicesToSettings_idx` (`settingID` ASC)  ,
  CONSTRAINT `FkDevicesToPositions`
    FOREIGN KEY (`positionID`)
    REFERENCES `energoremotedb`.`Positions` (`positionID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FkDevicesToGroups`
    FOREIGN KEY (`groupID`)
    REFERENCES `energoremotedb`.`Groups` (`groupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FkDevicesToSettings`
    FOREIGN KEY (`settingID`)
    REFERENCES `energoremotedb`.`Settings` (`settingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `energoremotedb`.`Notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `energoremotedb`.`Notifications` ;

CREATE TABLE IF NOT EXISTS `energoremotedb`.`Notifications` (
  `notificationID` INT(11) NOT NULL AUTO_INCREMENT ,
  `title` NVARCHAR(50) NOT NULL ,
  `text` NVARCHAR(240) NOT NULL ,
  PRIMARY KEY (`notificationID`)  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
